-- ============================================================
-- SEED DATA - admin account
-- FIXED CREDENTIALS - DO NOT CHANGE
-- Email    : admin@meditrack.com
-- Password : MediTrack@2026
-- BCrypt   : $2a$12$...  (auto-generated by Spring Boot DataSeeder)
-- ============================================================

USE meditrack_db;

-- NOTE: Admin is auto-seeded by Spring Boot DataSeeder.java on first startup.
-- This file is for reference and manual DB restore only.
-- Password hash below is BCrypt of "MediTrack@2026" with strength 12

INSERT INTO users
    (name, email, mobile, username, password, role, active)
VALUES
(
    'Central Admin',
    'admin@meditrack.com',
    NULL,
    'admin',
    '$2a$12$tFxS9cMBpxO9EHgk.Wr1.eIjxGZT4k0AX9bLBMWDFJBiqf1AQSV4G',
    'ADMIN',
    1
)
ON DUPLICATE KEY UPDATE
    name     = VALUES(name),
    role     = VALUES(role),
    active   = VALUES(active);

-- ============================================================
-- ADMIN LOGIN DETAILS (PERMANENT - NEVER CHANGE)
-- URL      : http://localhost:3000
-- Tab      : Staff Login -> Admin Tab
-- Email    : admin@meditrack.com
-- Password : MediTrack@2026
-- ============================================================