# Development profile overrides
spring.datasource.url=jdbc:mysql://localhost:3306/meditrack_db_dev?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
logging.level.com.meditrack=DEBUG4e3w